Acabades les descripcions de les assignatures del primer quadri
hwfib/hwfib.github.io pull request #22
Opened 2024-03-06 15:19 UTC by Serikpg

Ja he acabat la secció d'assignatures que he fet fins ara i que vam deixar a mitjes abans de la migració.
Oh meu zeus s'agraeix escriure en _Markdown_.

2024-03-06 17:15 UTC, raulgilabert submitted a review, later dismissed
LGTM :+1:

2024-03-06 17:32 UTC, rdvdev2 reviewed
Contingut guay, però crec que li cal una revisió gramatical. Hi ha alguna que altra frase molt llarga (i alguna paraula mal escrita). No crec que sigui com per no publicar-ho, però preferiria revisar-ho amb més calma quan pugui (al metro no jajaj).

2024-03-07 05:45 UTC, polsahi approved these changes
LGTM

2024-03-08 08:16 UTC, rdvdev2 approved these changes
Ara sí, LGTM!

2024-03-08 15:16 UTC, Serikpg commented
Gent, he corregit tot el text de les assignatures passant-lo pel SoftCatalà i afilant algunes frases... Ara sí que en teoria hauria d'estar llest per passar al main.

2024-03-09 12:59 UTC, raulgilabert requested changes

2024-03-09 12:59 UTC, raulgilabert commented on assigs.md
> +##### DSBM (Disseny de sistemes basats en microcontroladors)
![image](https://github.com/hwfib/hwfib.github.io/assets/12856430/29732225-5de5-4788-b249-982698ccb35e)

2024-03-10 09:08 UTC, Serikpg reviewed
He fet commit ja però nose com tornar a la PR

2024-03-10 12:32 UTC, rdvdev2 approved these changes
LGTM!

2024-03-10 12:33 UTC, rdvdev2 commented on assigs.md
>  ##### DSBM (Disseny de sistemes basats en microcomputadors)
Dubte ràpid, perquè estem saltant-nos nivells de heading (h3 -> h5)? A la web es veuen massa petits els títols i crec que és per culpa d'això.

2024-03-10 18:59 UTC, raulgilabert approved these changes
:+1:

2024-03-10 18:59 UTC, merged