Migració a jekyll
hwfib/hwfib.github.io pull request #7
Opened 2024-02-27 19:42 UTC by rdvdev2

Migració a Jekyll incloent l'extracció d'una plantilla amb el header, resol #5. Mantinc la PR bloquejada fins que tanquem #6 i resolgui merge conflicts.

2024-02-27 23:55 UTC, raulgilabert commented
Sobre la migració a Jekyll potser podem aprofitar que es pot escriure el contigut en markdown per evitar HTML fora de layouts i facilitar la col·laboració de més gent al no haver d'aprendre HTML

2024-02-28 05:18 UTC, rdvdev2 commented
> Sobre la migració a Jekyll potser podem aprofitar que es pot escriure el contigut en markdown per evitar HTML fora de layouts i facilitar la col·laboració de més gent al no haver d'aprendre el llenguatge

Aquesta és bona, per mi ho faig sense problemes.

2024-02-28 07:02 UTC, Serikpg commented
Sisii!! Jo ja ho donava per suposat. Però haurem d'aprendre una mica sobre el procès de compilació.
@raulgilabert tu n'has tocat pas, de Jekyll?

2024-02-28 07:04 UTC, rdvdev2 commented
> Sisii!! Jo ja ho donava per suposat. Però haurem d'aprendre una mica sobre el procès de compilació. @raulgilabert tu n'has tocat pas, de Jekyll?

És automatic, el GitHub ho té activat. Simplement s'han de fer les modificacions que he fet aquí per a activar una plantilla per defecte.

2024-02-28 07:05 UTC, Serikpg commented
Okay, okay... Mola i no alhora, sentiments encontrados...

2024-02-29 10:22 UTC, rdvdev2 commented
Good to go, espero reviews :)

2024-02-29 11:02 UTC, raulgilabert requested changes

2024-02-29 11:10 UTC, rdvdev2 commented on assigs.html
> +>>>>>>> 870c5cf (Migració a jekyll)
Ups

2024-02-29 19:55 UTC, Serikpg approved these changes
Nice... Però el format no està en Markdown oi

2024-02-29 19:55 UTC, merged